# Generated by Django 6.0.5 on 2026-06-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='lawyers/profile_images/')),
                ('specialization', models.CharField(choices=[('Civil Law', 'Civil Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law'), ('Corporate Law', 'Corporate Law'), ('Property Law', 'Property Law'), ('Constitutional Law', 'Constitutional Law'), ('Tax Law', 'Tax Law'), ('Labor Law', 'Labor Law'), ('Immigration Law', 'Immigration Law'), ('Environmental Law', 'Environmental Law'), ('Other', 'Other')], max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('bar_association', models.CharField(blank=True, max_length=150)),
                ('education', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Comma separated values. Example: English,Nepali,Hindi', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office_address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
    ]
