# Generated by Django 6.0.5 on 2026-06-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_lawyerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyerprofile',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='full_name',
            field=models.CharField(default='Unknown Lawyer', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Example: English, Nepali, Hindi', max_length=255),
        ),
    ]
