# Generated by Django 6.0.5 on 2026-05-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('part', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('dhara', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_id', models.IntegerField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_ai.legaldocument')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
