# Generated by Django 6.0.5 on 2026-06-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0003_rag_system_upgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalchunk',
            options={'ordering': ['doc_id', 'chunk_index']},
        ),
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameIndex(
            model_name='legalchunk',
            new_name='legal_ai_le_doc_id_fa9462_idx',
            old_name='legal_ai_le_doc_id_idx',
        ),
        migrations.RenameIndex(
            model_name='legalchunk',
            new_name='legal_ai_le_section_ea70d0_idx',
            old_name='legal_ai_le_section_idx',
        ),
        migrations.RenameIndex(
            model_name='legalchunk',
            new_name='legal_ai_le_article_df8d48_idx',
            old_name='legal_ai_le_article_idx',
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='legal_ai.legaldocument'),
        ),
    ]
