# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("legal_ai", "0005_legaldocument_source_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("spider_name", models.CharField(default="law_commission", max_length=100)),
                ("status", models.CharField(
                    choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")],
                    default="running",
                    max_length=20,
                )),
                ("max_pages", models.PositiveIntegerField(default=50)),
                ("pages_crawled", models.PositiveIntegerField(default=0)),
                ("pages_processed", models.PositiveIntegerField(default=0)),
                ("pages_skipped", models.PositiveIntegerField(default=0)),
                ("pdfs_found", models.PositiveIntegerField(default=0)),
                ("pdfs_processed", models.PositiveIntegerField(default=0)),
                ("errors_count", models.PositiveIntegerField(default=0)),
                ("error_log", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="PipelineLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stage", models.CharField(max_length=50)),
                ("status", models.CharField(
                    choices=[("started", "Started"), ("success", "Success"), ("failed", "Failed")],
                    max_length=20,
                )),
                ("message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("crawl_run", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="pipeline_logs",
                    to="legal_ai.crawlrun",
                )),
                ("document", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="pipeline_logs",
                    to="legal_ai.legaldocument",
                )),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
