# Generated by Django 6.0.7 on 2026-07-21 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0007_remove_crawl_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.TextField()),
                ('clarification_question', models.TextField()),
                ('user_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('unknown_terms', models.JSONField(blank=True, default=list)),
                ('ambiguity_detected', models.BooleanField(default=False)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('detected_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='legal_ai.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='legal_ai_cl_status_ab193f_idx'), models.Index(fields=['conversation'], name='legal_ai_cl_convers_58b1b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('normalized_query', models.TextField(blank=True)),
                ('detected_language', models.CharField(default='en', max_length=10)),
                ('query_intent', models.CharField(blank=True, max_length=50)),
                ('retrieval_results', models.JSONField(blank=True, default=dict)),
                ('relevance_scores', models.JSONField(blank=True, default=list)),
                ('top_chunks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('document_required', 'Document Required'), ('document_added', 'Document Added'), ('closed', 'Closed')], default='new', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('document_required', models.BooleanField(default=False)),
                ('document_uploaded', models.BooleanField(default=False)),
                ('knowledge_base_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gaps', to='legal_ai.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='legal_ai_kn_status_61e788_idx'), models.Index(fields=['detected_language'], name='legal_ai_kn_detecte_a624df_idx'), models.Index(fields=['created_at'], name='legal_ai_kn_created_28354a_idx')],
            },
        ),
    ]
