# Generated by Django 6.0.7 on 2026-07-21 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0008_clarificationrequest_knowledgegap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('knowledge_gap', 'Knowledge Gap'), ('document_failed', 'Document Processing Failed'), ('index_rebuilt', 'Index Rebuilt'), ('system_alert', 'System Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge_gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='legal_ai.knowledgegap')),
                ('legal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='legal_ai.legaldocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='legal_ai_ad_status_45a1fd_idx'), models.Index(fields=['severity'], name='legal_ai_ad_severit_7f123b_idx'), models.Index(fields=['notification_type'], name='legal_ai_ad_notific_ef1689_idx')],
            },
        ),
    ]
