# Generated by Django 6.0.7 on 2026-07-21 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0009_adminnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=255)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('source_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='legal_ai_co_user_id_df4b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_archived'], name='legal_ai_co_user_id_6e56dd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='legal_ai_me_convers_5e3444_idx'),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_references', to='legal_ai.legalchunk'),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_references', to='legal_ai.legaldocument'),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='legal_ai.message'),
        ),
        migrations.AddIndex(
            model_name='sourcereference',
            index=models.Index(fields=['message'], name='legal_ai_so_message_6f787a_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcereference',
            index=models.Index(fields=['document'], name='legal_ai_so_documen_997592_idx'),
        ),
    ]
