# Generated by Django 6.0.7 on 2026-07-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0010_sourcereference_conversation_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalchunk',
            name='annex_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='annex_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='article_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='article_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='chapter_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='chunk_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='chunk_type',
            field=models.CharField(default='provision', max_length=50),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='citation_label',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='contextualized_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='corrected_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='document_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='hierarchy_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='jurisdiction',
            field=models.CharField(default='Nepal', max_length=100),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='language',
            field=models.CharField(default='ne', max_length=10),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='ocr_status',
            field=models.CharField(default='uncertain', max_length=20),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='paragraph_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='parent_chunk_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='part_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='part_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='pdf_page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='schedule_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='schedule_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='section_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='section_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='source_page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='source_page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalchunk',
            name='subclause_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['chunk_id'], name='legal_ai_le_chunk_i_de46d5_idx'),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['content_hash'], name='legal_ai_le_content_145aa6_idx'),
        ),
    ]
