# Generated by Django 6.0.7 on 2026-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0011_legalchunk_annex_number_legalchunk_annex_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalchunk',
            name='annex_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='annex_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='schedule_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='schedule_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
