# Generated by Django 6.0.7 on 2026-07-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0013_alter_legalchunk_article_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalchunk',
            name='parent_chunk_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
