# Generated by Django 6.0.7 on 2026-07-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0014_alter_legalchunk_parent_chunk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalchunk',
            name='chunk_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
