# Generated by Django 6.0.5 on 2026-07-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_ai', '0015_alter_legalchunk_chunk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalchunk',
            name='ocr_corrections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='article',
            field=models.CharField(blank=True, help_text='Deprecated: Use article_number', max_length=255),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='chapter',
            field=models.CharField(blank=True, help_text='Deprecated: Use chapter_number', max_length=255),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='clause',
            field=models.CharField(blank=True, help_text='Deprecated: Use clause_number', max_length=255),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='dhara',
            field=models.CharField(blank=True, help_text='Deprecated: Use section_number or article_number', max_length=255),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='part',
            field=models.CharField(blank=True, help_text='Deprecated: Use part_number', max_length=255),
        ),
        migrations.AlterField(
            model_name='legalchunk',
            name='section',
            field=models.CharField(blank=True, help_text='Deprecated: Use section_number', max_length=255),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['doc', 'article_number'], name='legal_ai_le_doc_id_1aed05_idx'),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['doc', 'section_number'], name='legal_ai_le_doc_id_dce1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['document_type'], name='legal_ai_le_documen_67a08a_idx'),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['language'], name='legal_ai_le_languag_920dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['chunk_type'], name='legal_ai_le_chunk_t_ac19e4_idx'),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['ocr_status'], name='legal_ai_le_ocr_sta_ec96a6_idx'),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['doc', 'article_number', 'chunk_index'], name='legal_ai_le_doc_id_7e5520_idx'),
        ),
        migrations.AddIndex(
            model_name='legalchunk',
            index=models.Index(fields=['doc', 'section_number', 'chunk_index'], name='legal_ai_le_doc_id_318ef9_idx'),
        ),
        # Unique constraint removed temporarily - will be added after fixing duplicates
        # migrations.AddConstraint(
        #     model_name='legalchunk',
        #     constraint=models.UniqueConstraint(fields=('doc', 'chunk_id'), name='unique_document_chunk_id'),
        # ),
    ]
